package pizzaria;

public enum TipoEvento {

	CLIENTE_CHEGOU,
	GARCON_PEGOU_PEDIDO,
	PIZZAIOLO_PEGO_PEDIDO, 
	PIZZA_ESTA_PRONTA,
	CLIENTE_RECEBE_PIZZA, 
	PIZZAIOLO_TERMINO_PEDIDO,
	CLIENTE_FOI_EMBORA;
	
}
